# Using alpine image for small size
FROM ruby:2.7.3

# Use virtual build-dependencies tag so we can remove these packages after bundle install
RUN apt-get update && \
  apt-get install -qq -y \
    build-essential \
    chrpath \
    chrony \
    curl \
    htop \
    imagemagick \
    unzip \
    vim \
    whois \
    zip #&& apt-get install build-dependency build-base ruby-dev mysql-dev postgresql-dev git sqlite-dev

# Set an environment variable where the Rails app is installed to inside of Docker image
ENV RAILS_ROOT /var/www/app

# make a new directory where our project will be copied
RUN mkdir -p $RAILS_ROOT

# Set working directory within container
WORKDIR $RAILS_ROOT

# Setting env up
ARG RAILS_ENV
ENV RAILS_ENV=$RAILS_ENV
ENV RAKE_ENV=$RAILS_ENV
ENV RACK_ENV=$RAILS_ENV

# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN gem install bundler:2.2.12

RUN bundle install

# Adding project files
COPY . .

EXPOSE 3000

CMD ["bin/startup.sh"]
